import type { Client, InStatement, Row } from '@libsql/client';
import type { EvidenceRepository } from '@/application/yie/evidence/evidence-repository';
import {
  CandidateCompanySchema, CandidateMentionSchema, CanonicalSourceSchema, DiscoveryCheckpointSchema,
  DiscoveryRunSchema, SearchAttemptSchema, SearchExecutionPlanSchema, SourceExcerptSchema,
  type CandidateCompany, type CandidateMention, type CanonicalSource, type ClaimEvidenceLink,
  type DiscoveryCheckpoint, type DiscoveryRun, type IdentityResolutionDecision, type ProposedClaim,
  type SearchAttempt, type SearchExecutionPlan, type SourceExcerpt, type SourceObservation,
} from '@/domain/yie/evidence-schemas';

const json = JSON.stringify;
const parse = (v: unknown) => JSON.parse(String(v));
const ignored = (sql: string) => sql.replace('INSERT INTO', 'INSERT OR IGNORE INTO');
const b = (v: unknown) => Boolean(Number(v));

export class TursoEvidenceRepository implements EvidenceRepository {
  constructor(private readonly db: Client) {}
  async nextRunVersion(id:string,version:number){const r=await this.db.execute({sql:'SELECT COALESCE(MAX(run_version),0)+1 v FROM yie_discovery_runs WHERE search_plan_id=? AND search_plan_version=?',args:[id,version]});return Number(r.rows[0].v);}
  async createRun(v:DiscoveryRun){v=DiscoveryRunSchema.parse(v);await this.db.execute({sql:`INSERT INTO yie_discovery_runs (id,session_id,intent_version,search_plan_id,search_plan_version,run_version,status,shadow_only,execution_mode,provider_key,started_at,completed_at,failed_at,cancelled_at,resumed_from_run_id,correlation_id,actor_provenance,query_budget,source_budget,candidate_budget,provider_request_count,provider_retry_count,total_provider_latency_ms,estimated_provider_cost,failure_code,failure_message_summary,metadata_json,created_at,updated_at) VALUES (${Array(29).fill('?')})`,args:[v.id,v.sessionId,v.intentVersion,v.searchPlanId,v.searchPlanVersion,v.runVersion,v.status,1,v.executionMode,v.providerKey,v.startedAt,v.completedAt,v.failedAt,v.cancelledAt,v.resumedFromRunId,v.correlationId,v.actorProvenance,v.queryBudget,v.sourceBudget,v.candidateBudget,v.providerRequestCount,v.providerRetryCount,v.totalProviderLatencyMs,v.estimatedProviderCost,v.failureCode,v.failureMessageSummary,json(v.metadata),v.createdAt,v.updatedAt]});}
  async getRun(id:string){const r=await this.db.execute({sql:'SELECT * FROM yie_discovery_runs WHERE id=?',args:[id]});return r.rows[0]?this.readRun(r.rows[0]):null;}
  async updateRun(v:DiscoveryRun){v=DiscoveryRunSchema.parse(v);await this.db.execute({sql:'UPDATE yie_discovery_runs SET status=?,execution_mode=?,started_at=?,completed_at=?,failed_at=?,resumed_from_run_id=?,provider_request_count=?,provider_retry_count=?,total_provider_latency_ms=?,failure_code=?,failure_message_summary=?,metadata_json=?,updated_at=? WHERE id=?',args:[v.status,v.executionMode,v.startedAt,v.completedAt,v.failedAt,v.resumedFromRunId,v.providerRequestCount,v.providerRetryCount,v.totalProviderLatencyMs,v.failureCode,v.failureMessageSummary,json(v.metadata),v.updatedAt,v.id]});}
  async insertExecutionPlan(v:SearchExecutionPlan){v=SearchExecutionPlanSchema.parse(v);const q:InStatement[]=[{sql:'INSERT INTO yie_search_execution_plans (run_id,execution_plan_version,search_plan_id,search_plan_version,fingerprint,plan_json,created_at) VALUES (?,?,?,?,?,?,?)',args:[v.runId,v.executionPlanVersion,v.searchPlanId,v.searchPlanVersion,v.fingerprint,json(v),v.createdAt]},...v.orderedExecutionSteps.map(s=>({sql:'INSERT INTO yie_search_execution_steps (run_id,execution_plan_version,step_id,search_plan_query_id,query_text,source_category,priority,execution_order,status,skip_reason,step_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)',args:[v.runId,v.executionPlanVersion,s.stepId,s.searchPlanQueryId,s.queryText,s.sourceCategory,s.priority,s.executionOrder,s.status,s.skipReason,json(s)]}))];await this.db.batch(q,'write');}
  async getExecutionPlan(runId:string){const r=await this.db.execute({sql:'SELECT plan_json FROM yie_search_execution_plans WHERE run_id=? ORDER BY execution_plan_version DESC LIMIT 1',args:[runId]});return r.rows[0]?SearchExecutionPlanSchema.parse(parse(r.rows[0].plan_json)):null;}
  async updateStep(runId:string,stepId:string,status:string,step:unknown){await this.db.execute({sql:'UPDATE yie_search_execution_steps SET status=?,step_json=? WHERE run_id=? AND step_id=?',args:[status,json(step),runId,stepId]});}
  async insertAttempt(v:SearchAttempt){v=SearchAttemptSchema.parse(v);await this.db.execute({sql:`INSERT INTO yie_search_attempts (id,run_id,execution_step_id,search_plan_query_id,attempt_number,provider_key,query_text,source_category,status,started_at,completed_at,latency_ms,result_count,retryable,error_code,error_summary,provider_request_metadata_json,estimated_cost) VALUES (${Array(18).fill('?')})`,args:[v.id,v.runId,v.executionStepId,v.searchPlanQueryId,v.attemptNumber,v.providerKey,v.queryText,v.sourceCategory,v.status,v.startedAt,v.completedAt,v.latencyMs,v.resultCount,Number(v.retryable),v.errorCode,v.errorSummary,json(v.providerRequestMetadata),v.estimatedCost]});}
  async listAttempts(runId:string){const r=await this.db.execute({sql:'SELECT * FROM yie_search_attempts WHERE run_id=? ORDER BY started_at,attempt_number',args:[runId]});return r.rows.map(x=>SearchAttemptSchema.parse({id:x.id,runId:x.run_id,executionStepId:x.execution_step_id,searchPlanQueryId:x.search_plan_query_id,attemptNumber:Number(x.attempt_number),providerKey:x.provider_key,queryText:x.query_text,sourceCategory:x.source_category,status:x.status,startedAt:x.started_at,completedAt:x.completed_at,latencyMs:Number(x.latency_ms),resultCount:Number(x.result_count),retryable:b(x.retryable),errorCode:x.error_code,errorSummary:x.error_summary,providerRequestMetadata:parse(x.provider_request_metadata_json),estimatedCost:x.estimated_cost}));}
  async upsertSource(v:CanonicalSource){v=CanonicalSourceSchema.parse(v);await this.db.execute({sql:ignored(`INSERT INTO yie_sources (id,canonical_url,normalized_url,original_url,domain,registrable_domain,source_type,source_category,title,publisher,published_at,retrieved_at,first_seen_at,last_seen_at,content_hash,excerpt_hash,language,http_status,retrieval_status,robots_or_access_note,provenance_json,metadata_json) VALUES (${Array(22).fill('?')})`),args:[v.id,v.canonicalUrl,v.normalizedUrl,v.originalUrl,v.domain,v.registrableDomain,v.sourceType,v.sourceCategory,v.title,v.publisher,v.publishedAt,v.retrievedAt,v.firstSeenAt,v.lastSeenAt,v.contentHash,v.excerptHash,v.language,v.httpStatus,v.retrievalStatus,v.robotsOrAccessNote,json(v.provenance),json(v.metadata)]});const r=await this.db.execute({sql:'SELECT * FROM yie_sources WHERE canonical_url=?',args:[v.canonicalUrl]});return this.readSource(r.rows[0]);}
  async insertObservation(v:SourceObservation){const r=await this.db.execute({sql:ignored(`INSERT INTO yie_source_observations (id,run_id,source_id,search_attempt_id,search_plan_query_id,execution_step_id,rank,provider_result_id,provider_snippet,retrieved_excerpt,matched_terms_json,discovered_at,retrieval_method,relevance_proposal,provenance_json,fingerprint) VALUES (${Array(16).fill('?')})`),args:[v.id,v.runId,v.sourceId,v.searchAttemptId,v.searchPlanQueryId,v.executionStepId,v.rank,v.providerResultId,v.providerSnippet,v.retrievedExcerpt,json(v.matchedTerms),v.discoveredAt,v.retrievalMethod,v.relevanceProposal,json(v.provenance),v.fingerprint]});return Number(r.rowsAffected)===1;}
  async insertExcerpt(v:SourceExcerpt){v=SourceExcerptSchema.parse(v);const r=await this.db.execute({sql:ignored('INSERT INTO yie_source_excerpts (id,source_id,run_id,excerpt_type,excerpt_text,character_start,character_end,section_heading,extractor,created_at,content_hash,provenance_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)'),args:[v.id,v.sourceId,v.runId,v.excerptType,v.excerptText,v.characterStart,v.characterEnd,v.sectionHeading,v.extractor,v.createdAt,v.contentHash,json(v.provenance)]});return Number(r.rowsAffected)===1;}
  async listExcerpts(runId:string){const r=await this.db.execute({sql:'SELECT * FROM yie_source_excerpts WHERE run_id=? ORDER BY created_at,id',args:[runId]});return r.rows.map(x=>SourceExcerptSchema.parse({id:x.id,sourceId:x.source_id,runId:x.run_id,excerptType:x.excerpt_type,excerptText:x.excerpt_text,characterStart:x.character_start===null?null:Number(x.character_start),characterEnd:x.character_end===null?null:Number(x.character_end),sectionHeading:x.section_heading,extractor:x.extractor,createdAt:x.created_at,contentHash:x.content_hash,provenance:parse(x.provenance_json)}));}
  async insertMention(v:CandidateMention){v=CandidateMentionSchema.parse(v);const r=await this.db.execute({sql:ignored(`INSERT INTO yie_candidate_mentions (id,run_id,source_id,source_excerpt_id,raw_name,normalized_name_proposal,legal_name_proposal,brand_name_proposal,website_proposal,location_proposal,industry_proposal,business_model_proposal,mention_context,extraction_method,extraction_confidence,validation_status,rejection_reason,entity_type,created_at,provenance_json,fingerprint) VALUES (${Array(21).fill('?')})`),args:[v.id,v.runId,v.sourceId,v.sourceExcerptId,v.rawName,v.normalizedNameProposal,v.legalNameProposal,v.brandNameProposal,v.websiteProposal,v.locationProposal,v.industryProposal,v.businessModelProposal,v.mentionContext,v.extractionMethod,v.extractionConfidence,v.validationStatus,v.rejectionReason,v.entityType,v.createdAt,json(v.provenance),v.fingerprint]});return Number(r.rowsAffected)===1;}
  async listMentions(runId:string){const r=await this.db.execute({sql:'SELECT * FROM yie_candidate_mentions WHERE run_id=? ORDER BY created_at,id',args:[runId]});return r.rows.map(x=>CandidateMentionSchema.parse({id:x.id,runId:x.run_id,sourceId:x.source_id,sourceExcerptId:x.source_excerpt_id,rawName:x.raw_name,normalizedNameProposal:x.normalized_name_proposal,legalNameProposal:x.legal_name_proposal,brandNameProposal:x.brand_name_proposal,websiteProposal:x.website_proposal,locationProposal:x.location_proposal,industryProposal:x.industry_proposal,businessModelProposal:x.business_model_proposal,mentionContext:x.mention_context,extractionMethod:x.extraction_method,extractionConfidence:Number(x.extraction_confidence),validationStatus:x.validation_status,rejectionReason:x.rejection_reason,entityType:x.entity_type,createdAt:x.created_at,provenance:parse(x.provenance_json),fingerprint:x.fingerprint}));}
  async listCandidates(){const r=await this.db.execute('SELECT * FROM yie_candidate_companies ORDER BY first_seen_at,id');return r.rows.map(x=>CandidateCompanySchema.parse({id:x.id,canonicalName:x.canonical_name,normalizedName:x.normalized_name,legalName:x.legal_name,brandNames:parse(x.brand_names_json),canonicalDomain:x.canonical_domain,canonicalWebsite:x.canonical_website,headquartersGeographyProposal:x.headquarters_geography_proposal,operatingGeographiesProposal:parse(x.operating_geographies_json),industryProposals:parse(x.industry_proposals_json),businessModelProposals:parse(x.business_model_proposals_json),status:x.status,mergeConfidence:Number(x.merge_confidence),firstSeenRunId:x.first_seen_run_id,firstSeenAt:x.first_seen_at,lastSeenAt:x.last_seen_at,provenance:parse(x.provenance_json),metadata:parse(x.metadata_json)}));}
  async persistResolution(i:{candidate?:CandidateCompany;mention:CandidateMention;decision:IdentityResolutionDecision}){const q:InStatement[]=[];if(i.candidate){const v=i.candidate;q.push({sql:ignored(`INSERT INTO yie_candidate_companies (id,canonical_name,normalized_name,legal_name,brand_names_json,canonical_domain,canonical_website,headquarters_geography_proposal,operating_geographies_json,industry_proposals_json,business_model_proposals_json,status,merge_confidence,first_seen_run_id,first_seen_at,last_seen_at,provenance_json,metadata_json) VALUES (${Array(18).fill('?')})`),args:[v.id,v.canonicalName,v.normalizedName,v.legalName,json(v.brandNames),v.canonicalDomain,v.canonicalWebsite,v.headquartersGeographyProposal,json(v.operatingGeographiesProposal),json(v.industryProposals),json(v.businessModelProposals),v.status,v.mergeConfidence,v.firstSeenRunId,v.firstSeenAt,v.lastSeenAt,json(v.provenance),json(v.metadata)]});}const target=i.candidate?.id??i.decision.targetCandidateId;if(target)q.push({sql:ignored('INSERT INTO yie_candidate_mention_links (id,candidate_company_id,candidate_mention_id,source_id,run_id,created_at) VALUES (?,?,?,?,?,?)'),args:[`link-${i.mention.id}`,target,i.mention.id,i.mention.sourceId,i.mention.runId,i.decision.createdAt]});if(target)q.push({sql:ignored('INSERT INTO yie_candidate_company_aliases (id,candidate_company_id,alias,normalized_alias,alias_type,source_id,created_at) VALUES (?,?,?,?,?,?,?)'),args:[`alias-`,target,i.mention.rawName,i.mention.normalizedNameProposal,'SOURCE_MENTION',i.mention.sourceId,i.decision.createdAt]});const d=i.decision;q.push({sql:ignored('INSERT INTO yie_identity_resolution_decisions (id,run_id,action,source_candidate_id,target_candidate_id,mention_id,confidence,matched_signals_json,conflicting_signals_json,explanation,review_required,created_at,provenance_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)'),args:[d.id,d.runId,d.action,d.sourceCandidateId,target,d.mentionId,d.confidence,json(d.matchedSignals),json(d.conflictingSignals),d.explanation,Number(d.reviewRequired),d.createdAt,json(d.provenance)]});await this.db.batch(q,'write');return target;}
  async persistClaim(c:ProposedClaim,e:ClaimEvidenceLink){const r=await this.db.batch([{sql:ignored('INSERT INTO yie_proposed_claims (id,run_id,candidate_company_id,claim_type,normalized_value_json,raw_value_json,claim_status,extraction_confidence,source_count,created_at,updated_at,provenance_json,fingerprint) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)'),args:[c.id,c.runId,c.candidateCompanyId,c.claimType,json(c.normalizedValue),json(c.rawValue),c.claimStatus,c.extractionConfidence,c.sourceCount,c.createdAt,c.updatedAt,json(c.provenance),c.fingerprint]},{sql:ignored('INSERT INTO yie_claim_evidence_links (id,claim_id,source_id,source_excerpt_id,source_observation_id,support_type,extracted_text,relevance_confidence,created_at,provenance_json,fingerprint) VALUES (?,?,?,?,?,?,?,?,?,?,?)'),args:[e.id,e.claimId,e.sourceId,e.sourceExcerptId,e.sourceObservationId,e.supportType,e.extractedText,e.relevanceConfidence,e.createdAt,json(e.provenance),e.fingerprint]}],'write');return Number(r[0].rowsAffected)===1;}
  async appendCheckpoint(v:DiscoveryCheckpoint){v=DiscoveryCheckpointSchema.parse(v);const r=await this.db.execute({sql:ignored('INSERT INTO yie_discovery_checkpoints (id,run_id,checkpoint_type,sequence,status,reference_id,created_at,payload_summary,fingerprint,provenance_json) VALUES (?,?,?,?,?,?,?,?,?,?)'),args:[v.id,v.runId,v.checkpointType,v.sequence,v.status,v.referenceId,v.createdAt,v.payloadSummary,v.fingerprint,json(v.provenance)]});return Number(r.rowsAffected)===1;}
  async listCheckpoints(runId:string){const r=await this.db.execute({sql:'SELECT * FROM yie_discovery_checkpoints WHERE run_id=? ORDER BY sequence',args:[runId]});return r.rows.map(x=>DiscoveryCheckpointSchema.parse({id:x.id,runId:x.run_id,checkpointType:x.checkpoint_type,sequence:Number(x.sequence),status:x.status,referenceId:x.reference_id,createdAt:x.created_at,payloadSummary:x.payload_summary,fingerprint:x.fingerprint,provenance:parse(x.provenance_json)}));}
  async replay(runId:string){const counts:Record<string,number>={};for(const table of ['yie_search_attempts','yie_source_observations','yie_source_excerpts','yie_candidate_mentions','yie_identity_resolution_decisions','yie_proposed_claims','yie_discovery_checkpoints']){const r=await this.db.execute({sql:`SELECT COUNT(*) n FROM ${table} WHERE run_id=?`,args:[runId]});counts[table]=Number(r.rows[0].n);}return{run:await this.getRun(runId),plan:await this.getExecutionPlan(runId),counts,attempts:await this.listAttempts(runId),mentions:await this.listMentions(runId),checkpoints:await this.listCheckpoints(runId)};}
  private readRun(x:Row){return DiscoveryRunSchema.parse({id:x.id,sessionId:x.session_id,intentVersion:Number(x.intent_version),searchPlanId:x.search_plan_id,searchPlanVersion:Number(x.search_plan_version),runVersion:Number(x.run_version),status:x.status,shadowOnly:b(x.shadow_only),executionMode:x.execution_mode,providerKey:x.provider_key,startedAt:x.started_at,completedAt:x.completed_at,failedAt:x.failed_at,cancelledAt:x.cancelled_at,resumedFromRunId:x.resumed_from_run_id,correlationId:x.correlation_id,actorProvenance:x.actor_provenance,queryBudget:Number(x.query_budget),sourceBudget:Number(x.source_budget),candidateBudget:Number(x.candidate_budget),providerRequestCount:Number(x.provider_request_count),providerRetryCount:Number(x.provider_retry_count),totalProviderLatencyMs:Number(x.total_provider_latency_ms),estimatedProviderCost:x.estimated_provider_cost===null?null:Number(x.estimated_provider_cost),failureCode:x.failure_code,failureMessageSummary:x.failure_message_summary,metadata:parse(x.metadata_json),createdAt:x.created_at,updatedAt:x.updated_at});}
  private readSource(x:Row){return CanonicalSourceSchema.parse({id:x.id,canonicalUrl:x.canonical_url,normalizedUrl:x.normalized_url,originalUrl:x.original_url,domain:x.domain,registrableDomain:x.registrable_domain,sourceType:x.source_type,sourceCategory:x.source_category,title:x.title,publisher:x.publisher,publishedAt:x.published_at,retrievedAt:x.retrieved_at,firstSeenAt:x.first_seen_at,lastSeenAt:x.last_seen_at,contentHash:x.content_hash,excerptHash:x.excerpt_hash,language:x.language,httpStatus:x.http_status===null?null:Number(x.http_status),retrievalStatus:x.retrieval_status,robotsOrAccessNote:x.robots_or_access_note,provenance:parse(x.provenance_json),metadata:parse(x.metadata_json)});}
}


