import assert from 'node:assert/strict';
import { GeminiLiveEvidenceProvider } from '../src/infrastructure/yie/ai/gemini-live-evidence-provider';
import { CURRENT_WORKING_GEMINI_DEFAULT, loadGeminiModelPolicy } from '../src/infrastructure/yie/ai/gemini-model-policy';
import type { NeutralGeminiClient, NeutralGeminiResponse } from '../src/infrastructure/yie/ai/gemini-adapter';
import { ProviderError } from '../src/application/yie/providers/provider-errors';
import { canonicalizePublicUrl } from '../src/domain/yie/source-policy';
import { validateClaimWithEvidence, validateMention } from '../src/domain/yie/candidate-evidence-policy';
import { DiscoveryReplayService } from '../src/application/yie/evidence/evidence-execution-service';
import type { EvidenceRepository } from '../src/application/yie/evidence/evidence-repository';

class MockClient implements NeutralGeminiClient {calls=0;constructor(private readonly responses:Array<NeutralGeminiResponse|Error|Promise<NeutralGeminiResponse>>){}async generate(){this.calls++;const next=this.responses.shift();if(next instanceof Error)throw next;if(!next)throw new Error('No mocked Gemini response.');return await next;}}
const budget={timeoutMs:100,maxRetries:0,maxOutputTokens:2000};
async function main(){let assertions=0;const ok=(v:unknown)=>{assert.ok(v);assertions++;};const models=loadGeminiModelPolicy({});assert.equal(models.DISCOVER_CANDIDATES,CURRENT_WORKING_GEMINI_DEFAULT);assertions++;
  const grounded=new MockClient([{text:JSON.stringify({results:[{groundingSourceKey:'grounding-1',snippet:'Acme Foods LLC is a California distributor.',title:'Acme profile',sourceType:'INDUSTRY_DIRECTORY',modelEmittedUrl:'https://model-only.example/acme'}],modelEmittedUrls:['https://another-model-only.example']}),requestId:'mock-grounded',groundingSources:[{url:'https://directory.example/acme?utm_source=google',title:'Directory Acme'},{url:'https://unused-grounding.example',title:'Unused'}]}]);const provider=new GeminiLiveEvidenceProvider(grounded,models,()=>new Date('2026-07-31T12:00:00.000Z'));const search=await provider.executeSearchQuery({queryId:'q1',queryText:'accepted query',sourceCategory:'DIRECTORY',maximumResults:5,budget});assert.equal(grounded.calls,1);assertions++;assert.equal(search.metadata.model,CURRENT_WORKING_GEMINI_DEFAULT);assertions++;assert.equal(search.value.groundingSourcesReceived,2);assertions++;assert.equal(search.value.modelEmittedUrlsReceived,2);assertions++;assert.equal(search.value.sources.length,1);assertions++;assert.equal(search.value.sources[0].url,'https://directory.example/acme?utm_source=google');assertions++;ok(!search.value.sources.some(x=>x.url.includes('model-only')));assert.equal(search.value.sources[0].groundingSourceKey,'grounding-1');assertions++;
  const canonicalA=canonicalizePublicUrl(search.value.sources[0].url).canonicalUrl,canonicalB=canonicalizePublicUrl('https://www.directory.example/acme?utm_campaign=x').canonicalUrl;assert.equal(canonicalA,canonicalB);assertions++;
  const malformed=new GeminiLiveEvidenceProvider(new MockClient([{text:'not-json',groundingSources:[]}]),models);await assert.rejects(()=>malformed.executeSearchQuery({queryId:'q2',queryText:'accepted query',sourceCategory:'WEB',maximumResults:2,budget}),e=>e instanceof ProviderError&&e.code==='MALFORMED_RESPONSE');assertions++;
  const timeout=new GeminiLiveEvidenceProvider(new MockClient([new Promise<NeutralGeminiResponse>(()=>{})]),models);await assert.rejects(()=>timeout.executeSearchQuery({queryId:'q3',queryText:'accepted query',sourceCategory:'WEB',maximumResults:2,budget:{...budget,timeoutMs:1}}),e=>e instanceof ProviderError&&e.code==='TIMEOUT');assertions++;
  const partialClient=new MockClient([{text:JSON.stringify({results:[{groundingSourceKey:'grounding-1',snippet:'First Company LLC is listed.',sourceType:'INDUSTRY_DIRECTORY'}],modelEmittedUrls:[]}),groundingSources:[{url:'https://directory.example/first'}]},new Error('503 upstream unavailable')]);const partial=new GeminiLiveEvidenceProvider(partialClient,models);const first=await partial.executeSearchQuery({queryId:'accepted-1',queryText:'first accepted',sourceCategory:'WEB',maximumResults:2,budget});assert.equal(first.value.sources.length,1);assertions++;await assert.rejects(()=>partial.executeSearchQuery({queryId:'accepted-2',queryText:'second accepted',sourceCategory:'WEB',maximumResults:2,budget}),e=>e instanceof ProviderError&&e.retryable);assertions++;assert.equal(partialClient.calls,2);assertions++;
  const extractionClient=new MockClient([{text:JSON.stringify({mentions:[{rawName:'Acme Foods',normalizedNameProposal:'Acme Foods',mentionContext:'Acme Foods LLC is a California distributor.',entityType:'COMPANY',confidence:.9}]})},{text:JSON.stringify({claims:[{claimType:'LOCATION',normalizedValue:'California',rawValue:'California',supportType:'DIRECT_TEXT',extractedText:'Acme Foods LLC is a California distributor.',confidence:.9}]})}]);const extraction=new GeminiLiveEvidenceProvider(extractionClient,models);const excerpt='Acme Foods LLC is a California distributor.';const mentionProposal=(await extraction.extractCandidateMentions({sourceUrl:'https://directory.example/acme',excerpt,budget})).value[0];const mention=validateMention({id:'mention-1',runId:'run-1',sourceId:'source-1',sourceExcerptId:'excerpt-1',proposal:mentionProposal,evidenceText:excerpt,createdAt:'2026-07-31T12:00:00.000Z'});assert.equal(mention.validationStatus,'ACCEPTED');assertions++;const unsupported=validateMention({id:'mention-2',runId:'run-1',sourceId:'source-1',proposal:{...mentionProposal,rawName:'Unsupported Company',normalizedNameProposal:'Unsupported Company'},evidenceText:excerpt,createdAt:'2026-07-31T12:00:00.000Z'});assert.equal(unsupported.validationStatus,'REJECTED');assertions++;
  const claimProposal=(await extraction.extractProposedClaims({companyName:'Acme Foods',sourceUrl:'https://directory.example/acme',excerpt,budget})).value[0];const linked=validateClaimWithEvidence({claimId:'claim-1',evidenceId:'evidence-1',runId:'run-1',candidateCompanyId:'candidate-1',sourceId:'source-1',sourceExcerptId:'excerpt-1',proposal:claimProposal,createdAt:'2026-07-31T12:00:00.000Z'});assert.equal(linked.evidence.claimId,linked.claim.id);assertions++;assert.equal(linked.evidence.sourceExcerptId,'excerpt-1');assertions++;assert.throws(()=>validateClaimWithEvidence({claimId:'bad',evidenceId:'bad-e',runId:'run-1',candidateCompanyId:'candidate-1',sourceId:'source-1',proposal:{claimType:'OTHER',normalizedValue:'needs Yorbis',rawValue:'needs Yorbis',supportType:'INFERRED_FROM_CONTEXT',extractedText:'This company needs Yorbis',confidence:.5},createdAt:'2026-07-31T12:00:00.000Z'}),/cannot persist qualification/);assertions++;
  let replayReads=0;const replayProviderCalls=grounded.calls+partialClient.calls+extractionClient.calls;const replay=new DiscoveryReplayService({replay:async(runId:string)=>{replayReads++;return{runId};}} as unknown as EvidenceRepository);assert.deepEqual(await replay.replay('run-1'),{runId:'run-1'});assertions++;assert.equal(replayReads,1);assertions++;assert.equal(grounded.calls+partialClient.calls+extractionClient.calls,replayProviderCalls);assertions++;
  console.log(`Pocket 5.1 mocked live-provider acceptance: ${assertions} assertions passed.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});

