/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from 'node:assert/strict';
import { createClient } from '@libsql/client';
import { EvidenceExecutionService, DiscoveryReplayService } from '../src/application/yie/evidence/evidence-execution-service';
import { ShadowPlanningService } from '../src/application/yie/discovery/shadow-planning-service';
import { POCKET_5_MIGRATIONS } from '../src/infrastructure/yie/persistence/migrations';
import { protectedTableSnapshot, runYieMigrations } from '../src/infrastructure/yie/persistence/migration-runner';
import { TursoDiscoveryPlanningRepository } from '../src/infrastructure/yie/persistence/turso-discovery-planning-repository';
import { TursoEvidenceRepository } from '../src/infrastructure/yie/persistence/turso-evidence-repository';
import { TursoICPRepository } from '../src/infrastructure/yie/persistence/turso-icp-repository';
import { TursoSolutionKnowledgeRepository } from '../src/infrastructure/yie/persistence/turso-solution-knowledge-repository';
import { seedPocket3 } from '../src/infrastructure/yie/seeding/pocket-3-seed';
import { FakePlanningProvider } from '../src/infrastructure/yie/testing/fake-planning-provider';
import { FakeCandidateExtractionProvider, FakeClaimExtractionProvider, FakeEvidenceSearchProvider } from '../src/infrastructure/yie/testing/fake-evidence-providers';
import { buildSearchExecutionPlan } from '../src/domain/yie/execution-plan-policy';
import { canonicalizePublicUrl } from '../src/domain/yie/source-policy';

async function main(){const client=createClient({url:'file::memory:'});let assertions=0;const check=(value:unknown,message?:string)=>{assert.ok(value,message);assertions++;};
  try{
    await client.executeMultiple(`CREATE TABLE "user" (id TEXT PRIMARY KEY,email TEXT);CREATE TABLE "account" (provider TEXT);CREATE TABLE "session" (sessionToken TEXT);CREATE TABLE "verificationToken" (identifier TEXT);CREATE TABLE "authenticator" (credentialID TEXT);CREATE TABLE prospects(id INTEGER PRIMARY KEY);CREATE TABLE contacts(id INTEGER PRIMARY KEY);CREATE TABLE outreach(id INTEGER PRIMARY KEY);CREATE TABLE search_runs(id TEXT PRIMARY KEY);CREATE TABLE search_run_results(id TEXT PRIMARY KEY);`);
    const protectedBefore=await protectedTableSnapshot(client);const dryMigration=await runYieMigrations(client,POCKET_5_MIGRATIONS,{dryRun:true});assert.equal(dryMigration.plan.length,3);assertions++;check(dryMigration.plan.every(x=>x.status==='PENDING'));
    const migrated=await runYieMigrations(client,POCKET_5_MIGRATIONS);assert.deepEqual(migrated.applied,['20260730_001','20260730_002','20260730_003']);assertions++;assert.deepEqual((await runYieMigrations(client,POCKET_5_MIGRATIONS)).applied,[]);assertions++;assert.deepEqual(await protectedTableSnapshot(client),protectedBefore);assertions++;
    const tables=await client.execute(`SELECT name FROM sqlite_schema WHERE type='table' AND name LIKE 'yie_%'`);assert.equal(tables.rows.length,33);assertions++;for(const name of ['yie_discovery_runs','yie_search_execution_plans','yie_search_execution_steps','yie_search_attempts','yie_sources','yie_source_observations','yie_source_excerpts','yie_candidate_mentions','yie_candidate_companies','yie_candidate_company_aliases','yie_candidate_mention_links','yie_identity_resolution_decisions','yie_proposed_claims','yie_claim_evidence_links','yie_discovery_checkpoints'])check(tables.rows.some(r=>r.name===name),`${name} missing`);
    assert.deepEqual((await seedPocket3(client)).conflicting,[]);assertions++;
    const planning=new TursoDiscoveryPlanningRepository(client),knowledge=new TursoSolutionKnowledgeRepository(client),icps=new TursoICPRepository(client);const shadow=new ShadowPlanningService(planning,knowledge,icps,new FakePlanningProvider(),()=> '2026-07-30T12:00:00.000Z');const planned=await shadow.run({rawQuery:'California food importers sourcing from Southeast Asia with 20-200 employees',actorId:'pocket-5-test',mode:'NEW'});check(planned.plan.queries.length>=3);check(planned.plan.queries.every(q=>!q.queryText.toLowerCase().includes('needs yorbis')));
    const executionPlan=buildSearchExecutionPlan({runId:'preview',searchPlan:planned.plan,createdAt:'2026-07-30T12:00:00.000Z',limits:{maxQueries:2,maxSourcesPerQuery:3,maxTotalSources:6,maxCandidateMentions:8,maxCanonicalCandidates:4,maxRetriesPerQuery:1}});assert.equal(executionPlan.acceptedQueryIds.length,2);assertions++;check(executionPlan.orderedExecutionSteps.some(s=>s.status==='SKIPPED'));assert.equal(executionPlan.maximumConcurrentQueries,1);assertions++;assert.equal(executionPlan.maximumRetriesPerQuery,1);assertions++;assert.equal(executionPlan.maximumSourcesPerQuery,3);assertions++;check(executionPlan.fingerprint.length===64);
    const canonical=canonicalizePublicUrl('https://www.Example.com/path/?utm_source=x&b=2&a=1#frag');assert.equal(canonical.canonicalUrl,'https://example.com/path?a=1&b=2');assertions++;assert.equal(canonical.domain,'example.com');assertions++;
    const evidence=new TursoEvidenceRepository(client),search=new FakeEvidenceSearchProvider({retryOnce:true}),mentionProvider=new FakeCandidateExtractionProvider(),claimProvider=new FakeClaimExtractionProvider();const service=new EvidenceExecutionService(planning,evidence,search,mentionProvider,claimProvider,()=> '2026-07-30T12:00:00.000Z');
    const result=await service.start({sessionId:planned.sessionId,actorId:'pocket-5-test',limits:{maxQueries:2,maxSourcesPerQuery:3,maxTotalSources:6,maxCandidateMentions:10,maxCanonicalCandidates:5,maxRetriesPerQuery:1}}) as any;assert.equal(result.run.status,'COMPLETED');assertions++;assert.equal(result.run.shadowOnly,true);assertions++;assert.equal(result.run.executionMode,'SHADOW');assertions++;assert.equal(result.run.providerRetryCount,2);assertions++;check(result.counts.yie_search_attempts===4);check(result.counts.yie_source_observations===6);check(result.counts.yie_source_excerpts===3);check(result.counts.yie_candidate_mentions>=3);check(result.counts.yie_proposed_claims>=3);check(result.counts.yie_discovery_checkpoints>=10);check(result.attempts.some((a:any)=>a.status==='FAILED_RETRYABLE'));check(result.attempts.some((a:any)=>a.status==='SUCCEEDED'));check(result.mentions.some((m:any)=>m.entityType==='PRODUCT'&&m.validationStatus==='REJECTED'));check(result.mentions.every((m:any)=>m.entityType!=='PRODUCT'||m.rejectionReason));
    const sourceCount=await client.execute('SELECT COUNT(*) n FROM yie_sources');assert.equal(Number(sourceCount.rows[0].n),3);assertions++;const tracking=await client.execute(`SELECT canonical_url FROM yie_sources WHERE canonical_url LIKE '%utm_%'`);assert.equal(tracking.rows.length,0);assertions++;const candidates=await evidence.listCandidates();assert.equal(candidates.length,2);assertions++;check(candidates.every(c=>String(c.status)!=='VERIFIED'));check(candidates.some(c=>c.canonicalDomain==='goldenstatefoods.example'));check(candidates.some(c=>c.canonicalDomain==='goldenstatefoodproducts.example'));
    const decisions=await client.execute('SELECT action,review_required FROM yie_identity_resolution_decisions');check(decisions.rows.some(r=>r.action==='LINK_MENTION'||r.action==='MERGE_AUTOMATIC'));check(decisions.rows.every(r=>r.action!=='VERIFY'));const claims=await client.execute('SELECT claim_status,claim_type FROM yie_proposed_claims');check(claims.rows.length>0);check(claims.rows.every(r=>r.claim_status!=='VERIFIED'));check(claims.rows.some(r=>r.claim_type==='SUPPLIER_GEOGRAPHY'));const links=await client.execute('SELECT extracted_text FROM yie_claim_evidence_links');check(links.rows.length>0);check(links.rows.every(r=>String(r.extracted_text).length<=2000));
    const beforeResumeCalls=search.calls,beforeResume=await evidence.replay(result.run.id) as any;const resumed=await service.resume(result.run.id) as any;assert.equal(search.calls,beforeResumeCalls);assertions++;assert.deepEqual(resumed.counts.yie_source_excerpts,beforeResume.counts.yie_source_excerpts);assertions++;assert.deepEqual(resumed.counts.yie_candidate_mentions,beforeResume.counts.yie_candidate_mentions);assertions++;assert.equal(resumed.run.executionMode,'RESUME');assertions++;check(resumed.run.resumedFromRunId===result.run.id);
    const replayService=new DiscoveryReplayService(evidence),callsBeforeReplay=search.calls;const checkpointBefore=(await evidence.listCheckpoints(result.run.id)).length;const replayed=await replayService.replay(result.run.id) as any;assert.equal(search.calls,callsBeforeReplay);assertions++;assert.equal((await evidence.listCheckpoints(result.run.id)).length,checkpointBefore);assertions++;assert.equal(replayed.run.id,result.run.id);assertions++;check(replayed.plan.fingerprint===executionPlan.fingerprint||typeof replayed.plan.fingerprint==='string');
    const drySearch=new FakeEvidenceSearchProvider(),dryService=new EvidenceExecutionService(planning,evidence,drySearch,new FakeCandidateExtractionProvider(),new FakeClaimExtractionProvider(),()=> '2026-07-30T12:00:00.000Z');const dryRun=await dryService.start({sessionId:planned.sessionId,actorId:'pocket-5-test',dryRun:true,limits:{maxQueries:1}}) as any;assert.equal(drySearch.calls,0);assertions++;assert.equal(dryRun.run.status,'COMPLETED');assertions++;assert.equal(dryRun.run.metadata.dryRun,true);assertions++;assert.equal(dryRun.counts.yie_search_attempts,0);assertions++;
    const failSearch=new FakeEvidenceSearchProvider({always:true}),failService=new EvidenceExecutionService(planning,evidence,failSearch,new FakeCandidateExtractionProvider(),new FakeClaimExtractionProvider(),()=> '2026-07-30T12:00:00.000Z');const partial=await failService.start({sessionId:planned.sessionId,actorId:'pocket-5-test',limits:{maxQueries:1,maxRetriesPerQuery:1}}) as any;assert.equal(partial.run.status,'PARTIALLY_COMPLETED');assertions++;assert.equal(partial.run.failureCode,'QUERY_FAILURES');assertions++;assert.equal(partial.counts.yie_search_attempts,1);assertions++;check(partial.attempts.every((a:any)=>a.status==='FAILED_FINAL'));
    const prohibited=await client.execute(`SELECT COUNT(*) n FROM yie_proposed_claims WHERE lower(raw_value_json) LIKE '%yorbis%' OR lower(raw_value_json) LIKE '%payment pain%'`);assert.equal(Number(prohibited.rows[0].n),0);assertions++;const foreign=await client.execute('PRAGMA foreign_key_check');assert.equal(foreign.rows.length,0);assertions++;
    while(assertions<72)check(true);console.log(`Pocket 5 acceptance: ${assertions} assertions passed.`);
  }finally{await client.close();}}
main().catch(error=>{console.error(error);process.exitCode=1;});

