import { z } from 'zod';
import type { CandidateExtractionProvider, ClaimExtractionProvider, EvidenceSearchProvider } from '@/application/yie/providers/evidence-providers';
import { CandidateMentionProposalSchema, ProposedClaimProposalSchema, SearchQueryResultSchema } from '@/application/yie/providers/evidence-providers';
import { ProviderError } from '@/application/yie/providers/provider-errors';
import type { ProviderBudget } from '@/application/yie/providers/ai-reasoning-provider';
import type { ProviderOperationMetadata } from '@/domain/yie/contracts';
import type { GeminiModelPolicy } from './gemini-model-policy';
import type { NeutralGeminiClient, NeutralGeminiResponse } from './gemini-adapter';
import { extractAndValidate } from './safe-json';

const GroundedResultSchema=z.object({results:z.array(z.object({groundingSourceKey:z.string().trim().min(1),snippet:z.string().trim().min(1).max(2000),title:z.string().trim().min(1).optional(),publisher:z.string().trim().min(1).optional(),sourceType:z.enum(['COMPANY_WEBSITE','TRADE_ASSOCIATION','INDUSTRY_DIRECTORY','GOVERNMENT_REGISTRY','BUSINESS_PUBLICATION','JOB_POSTING','PROFESSIONAL_PROFILE','IMPORT_RECORD','TRADE_SHOW_DIRECTORY','OTHER_PUBLIC_SOURCE']).default('OTHER_PUBLIC_SOURCE'),modelEmittedUrl:z.url().optional(),relevance:z.number().min(0).max(1).optional()}).strict()).max(50),modelEmittedUrls:z.array(z.url()).max(100).default([])}).strict();
const MentionResponseSchema=z.object({mentions:z.array(CandidateMentionProposalSchema).max(100)}).strict();
const ClaimResponseSchema=z.object({claims:z.array(ProposedClaimProposalSchema).max(100)}).strict();

async function timed<T>(promise:Promise<T>,timeoutMs:number){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new ProviderError('TIMEOUT','Gemini live evidence request timed out.',true,{provider:'gemini-live'})),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}
function failure(error:unknown){if(error instanceof ProviderError)return error;const message=error instanceof Error?error.message:String(error);if(/json|parse|schema|valid/i.test(message))return new ProviderError('MALFORMED_RESPONSE','Gemini returned malformed evidence output.',false,{provider:'gemini-live',cause:error});if(/429|rate.?limit/i.test(message))return new ProviderError('RATE_LIMIT','Gemini rate limit reached.',true,{provider:'gemini-live',cause:error});if(/5\d\d|upstream|unavailable/i.test(message))return new ProviderError('UPSTREAM','Gemini upstream request failed.',true,{provider:'gemini-live',cause:error});return new ProviderError('UNKNOWN','Gemini live evidence request failed.',false,{provider:'gemini-live',cause:error});}

export class GeminiLiveEvidenceProvider implements EvidenceSearchProvider,CandidateExtractionProvider,ClaimExtractionProvider {
  readonly providerId='gemini-live';
  constructor(private readonly client:NeutralGeminiClient,private readonly models:GeminiModelPolicy,private readonly now:()=>Date=()=>new Date()){}
  async executeSearchQuery(input:Parameters<EvidenceSearchProvider['executeSearchQuery']>[0]){
    const prompt=`Search the public web for companies matching this already-accepted search query: ${input.queryText}\nSource category: ${input.sourceCategory}\nReturn JSON only: {"results":[{"groundingSourceKey":"grounding-1","snippet":"verbatim factual snippet attributable to that grounding source","title":"title","sourceType":"OTHER_PUBLIC_SOURCE","modelEmittedUrl":"optional URL mentioned by the model","relevance":0.8}],"modelEmittedUrls":[]}\nUse only groundingSourceKey values corresponding to actual Google Search grounding chunks. Do not invent URLs or companies. Maximum results: ${input.maximumResults}.`;
    const {raw,metadata}=await this.generate(prompt,input.budget,true,'SEARCH_GROUNDED');
    let proposal:z.infer<typeof GroundedResultSchema>;try{proposal=extractAndValidate(raw.text,GroundedResultSchema);}catch(error){throw failure(error);}
    const grounding=(raw.groundingSources??[]).map((source,index)=>({key:`grounding-${index+1}`,url:source.url,title:source.title}));const byKey=new Map(grounding.map(x=>[x.key,x]));
    const modelUrls=[...proposal.modelEmittedUrls,...proposal.results.flatMap(x=>x.modelEmittedUrl?[x.modelEmittedUrl]:[])];
    const sources=proposal.results.flatMap((item,index)=>{const source=byKey.get(item.groundingSourceKey);if(!source)return[];return[{providerResultId:item.groundingSourceKey,url:source.url,title:item.title??source.title,publisher:item.publisher,snippet:item.snippet,rank:index+1,sourceType:item.sourceType,relevance:item.relevance,groundingSourceKey:item.groundingSourceKey,groundingProvider:'google-search'}];}).slice(0,input.maximumResults);
    return {value:SearchQueryResultSchema.parse({sources,groundingSourcesReceived:grounding.length,modelEmittedUrlsReceived:modelUrls.length,modelEmittedUrls:modelUrls}),metadata};
  }
  async extractCandidateMentions(input:Parameters<CandidateExtractionProvider['extractCandidateMentions']>[0]){const prompt=`Extract company mentions only from this persisted source excerpt. A mention must be textually supported. Source: ${input.sourceUrl}\nExcerpt: ${input.excerpt}\nReturn JSON only: {"mentions":[{"rawName":"name present in excerpt","normalizedNameProposal":"name","mentionContext":"supporting excerpt text","entityType":"COMPANY","confidence":0.8}]}. Products, people, publications and associations must use their correct entityType.`;const {raw,metadata}=await this.generate(prompt,input.budget,false,'EXTRACT_CANDIDATE_MENTIONS');try{return{value:extractAndValidate(raw.text,MentionResponseSchema).mentions,metadata};}catch(error){throw failure(error);}}
  async extractProposedClaims(input:Parameters<ClaimExtractionProvider['extractProposedClaims']>[0]){const prompt=`Extract only evidence-supported, unverified company claims for ${input.companyName} from this persisted excerpt. Source: ${input.sourceUrl}\nExcerpt: ${input.excerpt}\nReturn JSON only: {"claims":[{"claimType":"COMPANY_NAME","normalizedValue":"value","rawValue":"value","supportType":"DIRECT_TEXT","extractedText":"bounded supporting text from excerpt","confidence":0.8}]}. Never produce qualification, fit score, buying readiness, payment pain, volume, contact, decision-maker, or outreach claims.`;const {raw,metadata}=await this.generate(prompt,input.budget,false,'EXTRACT_PROPOSED_CLAIMS');try{return{value:extractAndValidate(raw.text,ClaimResponseSchema).claims,metadata};}catch(error){throw failure(error);}}
  private async generate(contents:string,budget:ProviderBudget,useGrounding:boolean,operation:string):Promise<{raw:NeutralGeminiResponse;metadata:ProviderOperationMetadata}>{const started=this.now();let raw:NeutralGeminiResponse;try{raw=await timed(this.client.generate({model:this.models.DISCOVER_CANDIDATES,contents,maxOutputTokens:budget.maxOutputTokens??4000,temperature:.1,useGrounding}),budget.timeoutMs);}catch(error){throw failure(error);}const completed=this.now();return{raw,metadata:{provider:this.providerId,model:this.models.DISCOVER_CANDIDATES,operation,requestId:raw.requestId??`gemini-live-${started.getTime()}`,startedAt:started.toISOString(),completedAt:completed.toISOString(),durationMs:Math.max(0,completed.getTime()-started.getTime()),retryCount:0,tokenUsage:raw.tokenUsage,groundingUsed:useGrounding,partialOutputAvailable:false}};}
}
